### ISSUE TITLE
Compiling proxy WinSCard.dll

### ISSUE THREAD

**Issue by WeyensLuk** [Fedict/eid-test-cards#4]
Hi,

The makefile provided to create the proxy WinSCard.dll is very environment specific. It depends on Visual Studio 2005 and several other dependencies. Instead of me spending time trying to recreate that specific environment, is it possible to provide a built version of this dll?
As a downloadable release?
Or alternatively an easier compilation process.

Thanks,
Luk

**Comment by Frederikus** [comment]
Hello Luk,

It is available here:
https://github.com/Fedict/eid-test-cards/releases

Wkr,
 Frederik
